[package]
name = "scan"
description = "A simple pager command-line application"
version = "0.1.0"
authors = ["Shresh7"]
repository = "https://github.com/Shresh7/scan"
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
crossterm = "0.28.1"
